### ISSUE TITLE
Does not display println statements

### ISSUE THREAD

**Issue by fterdal** [watchexec/cargo-watch#125]
I don't to see print statements when running cargo watch:

main.rs
```
fn main() {
    println!("Hello World");
}
```

When I `cargo run` directly, I see them as expected, but `cargo watch` shows me that the build succeeded and ran successfully, but no "Hello World". It re-runs every time the file changes. Just no output.

Btw, I'm rather new to Rust, so I might be missing something obvious (maybe a flag?). Thanks for making such a useful project!

> cargo watch --version
cargo-watch 6.0.0

**Comment by passcod** [comment]
Are you running `cargo watch` (which runs `cargo check` internally) or `cargo watch -x run` (which would run `cargo run`)?
