### ISSUE TITLE
Cargo commands (-x) are always executed before shell commands (-s) issue

### ISSUE THREAD

**Issue by daviscai** [watchexec/cargo-watch#148]
hope support execution in parameter order , e,g: 
cargo watch  -s 'rollup ./js/main.js --format iife --file ./js/bundle.js' -x run 
shell commands(-s)  executed before commands (-x)

but,  commands (-x) are always executed before shell commands (-s) , Is it possible to optimize ？

**Comment by passcod** [comment]
Prior: #124, #77.

This is a [clap](https://github.com/clap-rs/clap) limitation.

However, you can always use `-s 'cargo ...'` instead of `-x '...'`.

**Comment by passcod** [comment]
This is actually possible, and will be released soon in 8.0.0.

**Comment by passcod** [comment]
Done in 8.0.0
