### ISSUE TITLE
Incorrect expansion of wild card when using -x 

### ISSUE THREAD

**Issue by bidoubiwa** [watchexec/cargo-watch#178]
When I do write a path in my cargo arguments like this for example: 

```bash
cargo watch -x 'run -- misc/**/*' 
```

I expect fetching all files corresponding to the path. 
Unfortunately I only receive back what is nested inside that path. So only `misc/*/*` and not `misc/**/*`
When used in a simple cargo command: 
```bash
cargo run -- misc/**/* 
```
Files are well fetched. 

Code example used to reproduce: 

```rust
use std::env::args;


fn main() -> io::Result<()> {
  let arguments: Vec<_> = args().skip(1).collect();

  dbg!(arguments);
  return Ok(())
}
```

Wrong output: 

```
    "misc/array_test/far_away.json",
    "misc/array_test/far_behind.json",
    "misc/array_test/normal_array.json",
```

Right output: 
```
    "misc/array_test/far_away.json",
    "misc/array_test/far_behind.json",
    "misc/array_test/normal_array.json",
    "misc/nested_array.json",
    "misc/nested_array_2.json",
```

This is the file tree

```
misc
│   ├── far_away.json
│   ├── far_behind.json
│   └── normal_array.json
├── nested_array.json
├── nested_array_2.json
````

**Comment by passcod** [comment]
That's not really a bug. For the sake of explaining what's happening:

```bash
cargo run -- misc/**/* 
```

this does the expansion **in your shell, prior to executing cargo**. Presumably, your shell is bash, zsh, fish... but specifically, it's a shell with the [`globstar`](https://www.linuxjournal.com/content/globstar-new-bash-globbing-option) option enabled or built in. That's what makes `**` match subfolders.

In effect, what your shell actually runs is:

```bash
cargo run -- misc/array_test/far_away.json misc/array_test/far_behind.json misc/array_test/normal_array.json misc/nested_array.json misc/nested_array_2.json
```

---

When you run

```bash
cargo watch -x 'run -- misc/**/*'
```

the expansion is not done in your shell, but rather passed to cargo watch, which executes it with the default shell. Assuming unixen, this is `sh`, and that's most likely something like `dash` on Ubuntu or `bash` (maybe in "`sh`" mode, depends on your distro/setup). In any case, it's invoked as `sh -c "..."` which means that **none of the profile/rc files run**. Which means that, if it _is_ bash, the `globstar` option won't be enabled.

You can change the executing shell with `--shell`. You can pass options to the executing shell with `--shell="bash -some-option"` or whatnot. Someone recently did this in watchexec: https://github.com/watchexec/watchexec/issues/199 for the purposes of enabling aliases, but the same applies to globstar or whatever other advanced globbing behaviour you have enabled.

---

You can however use the long form invocation to run the globbing in your shell:

```bash
cargo watch -- cargo run -- misc/**/*
```

But! Keep in mind this will "actually" run:

```bash
cargo watch -- cargo run -- misc/array_test/far_away.json misc/array_test/far_behind.json misc/array_test/normal_array.json misc/nested_array.json misc/nested_array_2.json
```

You may be surprised later on when you create `misc/nested_array_3.json` and it "doesn't work".

**Comment by irevoire** [comment]
Do you think we could use the shell specified in the `$SHELL` env var as the default shell instead of relying on the system default shell?

**Comment by passcod** [comment]
That's a good idea, yeah.
