### ISSUE TITLE
How to run cargo watch run with color in Clion

### ISSUE THREAD

**Issue by SirMishaa** [watchexec/cargo-watch#180]
Hello ! 

I'm on Clion 2021.2 and when I'm using cargo watch, I don't have any colors :( 

So I see that I have to use `--color=always ` but how I pass it to the run command ? 

![image](https://user-images.githubusercontent.com/42717232/128606693-2b323d57-bde4-41e8-89cb-34f9ec9649bf.png)

Can't do that because I have this error : ``error: Found argument '--color' which wasn't expected, or isn't valid in this context``

**Comment by passcod** [comment]
Ah, that can be a little confusing. The `--color` option must be on the `cargo` command, not the `run` subcommand. The `-x` option in cargo watch only prepends the word `cargo`, so you can use:

```
cargo watch -x '--color=always run'
```

or

```
cargo watch -- cargo --color=always run
```

if the latter is more obvious.

**Comment by SirMishaa** [comment]
You're sure? I got the ``error: no such subcommand: `cargo``

**Comment by passcod** [comment]
To which? I haven't actually tested this, no, as I'm on my phone, but I'll take a closer look when able

**Comment by passcod** [comment]
I'm also unfamiliar with Clion, so I don't know if that's playing into it; if you're able to test in a terminal as well, that would be helpful

**Comment by SirMishaa** [comment]
Sorry, this is working good! I just had to remove the "cargo" because Clion already add it by default. 

Thanks, buddy!
