### ISSUE TITLE
Looking for  a way to reload browser after run is started

### ISSUE THREAD

**Issue by the-ica** [watchexec/cargo-watch#186]
I build a web server with actix, and whould like to reload the broser ( " firefox localhost:8080 " ... ) when the server is restarted after each compilation.

Although there are many option to run cargo command and shell bash, I did not found a way to do that.

**Comment by passcod** [comment]
It's a start, but at minimum that's going to open a new tab every time, see.

**Comment by the-ica** [comment]
My problem is not how to reload the browser, I can do something like that :  https://unix.stackexchange.com/questions/37258/refresh-reload-active-browser-tab-from-command-line

My problem is that watch run cargo commands first, and cargo run blocks ...

Maybe I should run the program directly without cargo ?

**Comment by passcod** [comment]
> My problem is that watch run cargo commands first, and cargo run blocks ...

That's not the case since version 8. If it is, that's a bug

**Comment by the-ica** [comment]
It block further bash command, ie if i do 
`cargo watch -x run -s "ls"`
ls is never executed

**Comment by passcod** [comment]
Right, so you want to run something *after* starting `cargo run`. That's not currently possible. Use a separate cargo watch, or try running a script that waits for a bit with disown before the run.

**Comment by the-ica** [comment]
This work : 

```
cargo watch -x build -s "pkill meet ; ./reload.sh & target/debug/meet"
cat reload.sh
#!/bin/bash
sleep .1 & xdotool key --window $(xdotool search --sync --all --onlyvisible --name firefox) CTRL+F5
```

Thanks for your help !
