### ISSUE TITLE
Watch is very slow on FreeBSD and `--clear` doesn't work

### ISSUE THREAD

**Issue by wisonye** [watchexec/cargo-watch#218]
- Super slow on FreeBSD to use watch feature, it takes around `20 sec` to see the refresh from `cargo run` command

- `--clear` doesn't work

    ```bash
    cargo watch --clear --exec run
    # [Running 'cargo run']
    # Error: ClearScreen error: Capability database not found.
    ```
   
    So, the temporary work around is ` cargo watch --shell "tput reset && cargo run"`

    </br>
    
OS info:
   
```bash
uname -a
# FreeBSD my-bsd 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64
```

**Comment by passcod** [comment]
We use polling on BSD. You can try reducing the interval with `--delay` though the default is already half a second. Try getting a verbose/debug log for more.

For clear: could you install

```
cargo install --example clscli clearscreen
```

and run it with

```
clscli auto
clscli auto | hexdump -C
```

and report the output?

Can uninstall it afterwards.

**Comment by wisonye** [comment]
> We use polling on BSD. You can try reducing the interval with `--delay` though the default is already half a second. Try getting a verbose/debug log for more.
> 
> For clear: could you install
> 
> ```
> cargo install --example clscli clearscreen
> ```
> 
> and run it with
> 
> ```
> clscli auto
> clscli auto | hexdump -C
> ```
> 
> and report the output?
> 
> Can uninstall it afterwards.

Yup, sure no worry, here is the result you asked for:

```bash
clscli auto
# variant = Terminfo, sleeping 1 second
# Error: ClearScreen(Terminfo(NotFound))


clscli auto | hexdump -C
# 00000000  76 61 72 69 61 6e 74 20  3d 20 54 65 72 6d 69 6e  |variant = Termin|
# 00000010  66 6f 2c 20 73 6c 65 65  70 69 6e 67 20 31 20 73  |fo, sleeping 1 s|
# Error: ClearScreen(Terminfo(NotFound))
# 00000020  65 63 6f 6e 64 0a                                 |econd.|
# 00000026
```

</br>

**Comment by passcod** [comment]
Right, of course, what was I thinking. We should definitely handle the error and fallback, but out of curiosity, what's your `$TERM`?

**Comment by passcod** [comment]
Also you probably can workaround by installing a terminfo, assuming that's a thing on BSDs.

**Comment by wisonye** [comment]
> 

I'm running a `alacritty` terminal and all commands are running in `tmux` sessions:

```bash
echo $TERM
# tmux-256color
```

</br>

**Comment by wisonye** [comment]
> Also you probably can workaround by installing a terminfo, assuming that's a thing on BSDs.

```bash
cargo install terminfo

#     Updating crates.io index
# error: there is nothing to install in `terminfo v0.7.3`, because it has no binaries
# `cargo install` is only for installing programs, and can't be used with libraries.
# To use a library crate, add it as a dependency in a Cargo project instead.
```

Then I installed `misc/terminfo-db               Terminal Description database`
and re-run the commands you asked for, nothing changes:)

Of courese, include this one (not changes):

```bash

cargo watch -c --exec run
# [Running 'cargo run']
# Error: ClearScreen error: Capability database not found.
```

</br>

Plz let me know if you still need anything from me, I hope I can hope to solve this issue:)

**Comment by passcod** [comment]
Hmm, I'll just support tmux explicitly in the future. But to workaround, you can set `TERM=screen-256color` (just for cargo watch, it will suffice).

**Comment by wisonye** [comment]
> 

Yup the `TERM=screen-256color cargo watch --clear --exec run` work perfectly:) Many thanks: )

**Comment by ryanavella** [comment]
I'm experiencing the same issue, and the suggestion to run `TERM=screen-256color cargo watch --clear --exec ...` doesn't seem to make a difference.

```
$ uname -imrs
FreeBSD 14.0-RELEASE-p5 amd64 GENERIC
```

I'm also running an alacritty terminal, though not with tmux, and my FreeBSD is the host and not a guest VM like OP.

```
$ echo $TERM
xterm-256color
```

```
$ clscli auto | hexdump -C
00000000  76 61 72 69 61 6e 74 20  3d 20 58 74 65 72 6d 43  |variant = XtermC|
00000010  6c 65 61 72 2c 20 73 6c  65 65 70 69 6e 67 20 31  |lear, sleeping 1|
00000020  20 73 65 63 6f 6e 64 0a  1b 5b 48 1b 5b 32 4a 1b  | second..[H.[2J.|
00000030  5b 33 4a                                          |[3J|
00000033
```

```
$ rustc --version --verbose
rustc 1.80.0-nightly (da159eb33 2024-05-28)
binary: rustc
commit-hash: da159eb331b27df528185c616b394bb0e1d2a4bd
commit-date: 2024-05-28
host: x86_64-unknown-freebsd
release: 1.80.0-nightly
LLVM version: 18.1.6
```

> We use polling on BSD.

I assume you mean polling for file modification times? If so, is there a technical reason that `kqueue` (or an OS-agnostic wrapper crate like `notify`) isn't used?

**Comment by passcod** [comment]
You'll notice that `notify` (_which I originally wrote for cargo watch_) is indeed used, just an older version that didn't support kqueue. Also please don't necropost.
