### ISSUE TITLE
From 8.2.0 .env file in root dir is ignored

### ISSUE THREAD

**Issue by frederikhors** [watchexec/cargo-watch#226]
Switching from 8.1.2 to 8.2.0 .env file in root dir is ignored.

I'm using this command:

```shell
cargo watch -x run --ignore "custom_dir"
```

**Comment by passcod** [comment]
Specifically, it does so for virtual workspaces (where there isn't a package at the top level)

**Comment by passcod** [comment]
Fixed in 8.2.1

**Comment by frederikhors** [comment]
I cannot try, still not present:

**Comment by frederikhors** [comment]
![image](https://user-images.githubusercontent.com/41120635/210014398-a8206fd0-58ca-426d-9571-75b647d17b0e.png)

**Comment by passcod** [comment]
Right, sorry, took me a while longer to get to crates.io publish, but that's done now.

**Comment by frederikhors** [comment]
It works now!
