### ISSUE TITLE
Intent to retire signatures, comment if you use them

### ISSUE THREAD

**Issue by passcod** [watchexec/cargo-watch#238]
#### ~~RPM and DEB~~
~~These show practically no usage in the download stats, so I'm going to simplify packaging and ditch them from the next major release onward. If this will break your workflow and you have no alternative, comment here!~~

After feedback, I'll keep those going.

#### Signatures

The `*.minisig` and `B3SUMS` and `SHA*SUMS` will be retired.

If you feel strongly against this, please comment here!

**Comment by apiraino** [comment]
I like having a musl Debian package ready for download, but if am an exception I can leave without that :slightly_smiling_face:
