### ISSUE TITLE
Support for non-rust projects.

### ISSUE THREAD

**Issue by Cthutu** [watchexec/cargo-watch#239]
I find `cargo-watch` to be a really useful tool and I find I want similar functionality in other domains.  It is quite common for me to run a command when a folder changes.  I tried this:
```
cargo watch -c -q -- just build
```
inside a non-Rust project.  Unsurprisingly, it didn't work and complained about not finding the project root.

I was wondering if there could be a flag that allows cargo-watch to run in a non-Rust project?

**Comment by passcod** [comment]
No. But [watchexec](https://github.com/watchexec/watchexec) (which cargo watch uses under the hood) exists for exactly this!
