### ISSUE TITLE
Can't install on fedora - "failed to select a version for the requirement `zbus = "^3.6"`"

### ISSUE THREAD

**Issue by RosaErick** [watchexec/cargo-watch#240]
### Hi everybody! 

I'm trying to install cargo-watch on fedora but I'm getting an error that I don't know how to handle and I can't find anything that helps. I'm posting here in hopes that someone has had the same problem and knows how to solve it, thanks in advance.

### Environment:

```
 uname -a
Linux fedora 5.19.4-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 25 17:42:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```
```
rustc -Vv 
rustc 1.59.0 (Fedora 1.59.0-4.fc36)
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.59.0
LLVM version: 13.0.1

```

```
cargo -Vv
cargo 1.59.0
release: 1.59.0
host: x86_64-unknown-linux-gnu
libgit2: 1.3.1 (sys:0.13.23 system)
libcurl: 7.82.0 (sys:0.4.51+curl-7.80.0 system ssl:OpenSSL/3.0.5)
os: OracleLinux 36.0.0 [64-bit]

```

### Installation

```
cargo install cargo-watch
    Updating crates.io index
  Installing cargo-watch v8.3.0
error: failed to compile `cargo-watch v8.3.0`, intermediate artifacts can be found at `/tmp/cargo-install5pQs21`

Caused by:
  failed to select a version for the requirement `zbus = "^3.6"`
  candidate versions found which didn't match: 2.3.2, 2.3.1, 2.3.0, ...
  location searched: crates.io index
  required by package `notify-rust v4.7.0`
      ... which satisfies dependency `notify-rust = "^4.7.0"` of package `cargo-watch v8.3.0`

```

**Comment by passcod** [comment]
Hmm, that's odd, because zbus definitely has those versions: https://crates.io/crates/zbus/versions
Might be a registry cache issue?

To install cargo-watch anyway you can use [binstall](https://github.com/cargo-bins/cargo-binstall) to install from binary. Given binstall doesn't depend on zbus it might compile for you...

**Comment by passcod** [comment]
Oh, but you're running rustc 1.59. You're going to run into issues anyway as cargo-watch requires 1.60 currently

**Comment by RosaErick** [comment]
thanks, updating rust fixed my problem!
