### ISSUE TITLE
Shell no longer displays characters after cargo watch -x run

### ISSUE THREAD

**Issue by kekonn** [watchexec/cargo-watch#254]
I have been using cargo watch to compile my project (`cargo watch -x run -d 5 -B 1 -L "info,fercord=debug,fercord::storage=trace"`) but every time after I use ctrl+c to stop cargo watch and the underlying process, the terminal stops accepting input (not printing typed characters). It does still respond to ctrl+c and ctrl+d.

I have verified that this behaviour exists in 4 different terminal emulators (alacritty, vs code terminal, kitty and gnome terminal/console). I am on arch and use bash (GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu))

rustup show prints:
```
✦ ❯ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/kekkon/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.67.0-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```

cargo watch --version prints:
```
✦ ❯ cargo watch --version
cargo-watch 8.4.0
```

**Comment by passcod** [comment]
can you explain a bit more about what it does? perhaps provide a screen recording or something like it if it's hard to describe? i'm not sure i get it

also a debug log of some kind

finally, is this a regression? have you tested with eg 8.3.0?

**Comment by kekonn** [comment]
I just tested with 8.3.0 and it still occurs. What kind of debug log are you looking for?

I will try to get a screen recording later today.

**Comment by passcod** [comment]
`cargo watch [your options] --debug` would be a great start

**Comment by kekonn** [comment]
So here's the strange thing. When i use --debug, the problem goes away.

**Comment by passcod** [comment]
Well, that's annoying. Deffo get a screen recording (with and without debug, for comparison), then.

**Comment by kekonn** [comment]
![image](https://user-images.githubusercontent.com/149670/221620154-ff2288b5-6792-414e-a21a-2366cc5bcb67.png)
The nightly version seems to have fixed it. Thanks!

**Comment by kekonn** [comment]
Sorry, previous message was for another thread. I did some further attempts and I am starting to suspect the behaviour is actually related to McFly, which I am using for shell history management. I noticed today that it started acting very weird. So let's consider this closed until I can pinpoint it further
