### ISSUE TITLE
Ignored directories are traversed and cause Error: I/O error: Permission denied (os error 13)

### ISSUE THREAD

**Issue by Skinner927** [watchexec/cargo-watch#264]
Hello,

I'm having a problem when there's  a directory in my working path that I don't have permission to access (it's a Docker mount if anyone cares).

Here's how to replicate (no need for Docker).

```bash
# Setup
mkdir good bad
chmod 0 bad

# This works if we explicitly only watch good (sanity check too)
cargo watch -C "$(pwd)" -w good -- bash -c 'echo bump'

cargo watch -C "$(pwd)" --ignore "*/bad/**/*" -- bash -c 'echo bump'
#> Error: I/O error: Permission denied (os error 13)
cargo watch -C "$(pwd)" --ignore "*/**/*" -- bash -c 'echo bump'
#> Error: I/O error: Permission denied (os error 13)
cargo watch -C "$(pwd)" --ignore "*" -- bash -c 'echo bump'
#> Error: I/O error: Permission denied (os error 13)
cargo watch -C "$(pwd)" --ignore "**" -- bash -c 'echo bump'
#> Error: I/O error: Permission denied (os error 13)
cargo watch -C "$(pwd)" --ignore "*bad*" -- bash -c 'echo bump'
#> Error: I/O error: Permission denied (os error 13)
```

Is there any way to workaround this other than using an "allow-only" by specifying `-w`?

Thank you

**Comment by passcod** [comment]
Yeah that's a known issue for now, will go away when we upgrade to Watchexec lib v2. You can use the watchexec CLI tool which has that fixed; it's not as nice for Cargo projects but can be adapted for use.

**Comment by Skinner927** [comment]
I couldn't find an open issue describing the same, but since it's already known I'll close this issue. Thanks for the workaround.
