### ISSUE TITLE
`rustc-ice-*.txt` files are watched, causing infinite loop of recompiling

### ISSUE THREAD

**Issue by kpreid** [watchexec/cargo-watch#277]
Newer versions of rustc (possibly nightly only?) automatically produce log files named like `rustc-ice-2023-08-21T15:55:30.315378Z-2018.txt` if the compiler panics. If `cargo watch` is used and the compiler panics, this will create an infinite loop as `cargo watch` sees the new file from each run and recompiles.

It would probably be good to ignore these files automatically.

**Comment by passcod** [comment]
Thanks! Added in 8.4.1
