### ISSUE TITLE
cargo-watch dependency quarantined

### ISSUE THREAD

**Issue by sahina** [watchexec/cargo-watch#279]
I am in a corporate environment and while trying to update cargo-watch, i see this error

```
Error while handling Cargo download request for path cargo-proxy:crates/nix/nix-0.22.3.crate : -------------------->>> REQUESTED ITEM IS QUARANTINED
```

Issue is with `nix : 0.22.3 : crate`, recommended solution is `Upgrade to 0.23.0`.

I didn't see an open issue to bump nix dependecy version.

**Comment by passcod** [comment]
> I didn't see an open issue to bump nix dependecy version.

Some of our dependencies use that version, and the biggest one (watchexec) isn't going to be updated for some time.

> I am in a corporate environment...

Ultimately this project is not responsible nor interested in complying with whatever insane rules some arbitrary 'corporate' software is applying. You may have better luck using the binary releases.
