### ISSUE TITLE
Argument grouping bug

### ISSUE THREAD

**Issue by Red44** [watchexec/cargo-watch#281]
# Grouping error
I am currently trying this on Windows 11 and noticed, that  '  is not working as it shut, grouping spaced commands into a singular argument.

Example: 
```bash
cargo watch -x 'build --release'
```
-------------------
Results in:
```txt
error: Found argument '--release'' which wasn't expected, or isn't valid in this context

USAGE:
    cargo watch [FLAGS] [OPTIONS]

For more information try --help
```
-----------------
Am I using the tool wrong, or is this assumption correct, that this is a bug?

Kind regards Jakob

**Comment by passcod** [comment]
You are not technically using the tool wrong, _and_ this is not a bug! This is, most likely, shell quoting issues. See e.g. https://superuser.com/questions/324278/how-to-make-windows-command-prompt-treat-single-quote-as-though-it-is-a-double-q
