### ISSUE TITLE
os error 5

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [watchexec/cargo-watch#295]
```
[Running 'cargo .']
Error: I/O error: Access is denied. (os error 5)
```

win7x64
rust  1.76.0-nightly

**Comment by passcod** [comment]
from the readme

![Screenshot_20231216-174501_GitHub.png](https://github.com/watchexec/cargo-watch/assets/155787/57e03968-0184-4248-b8db-346c869a8a5c)

**Comment by miaomiao1992** [comment]
thanks . i know，meeting the same problem.
