### ISSUE TITLE
Random compilation failures

### ISSUE THREAD

**Issue by erikschul** [watchexec/cargo-watch#300]
I'm not sure that this is a `cargo watch` problem.
I suspect that `cargo watch -x build` sometimes runs concurrently with `rust-analyzer` (and `clippy`), in a way where two compilations interfere. Maybe one deletes the target folder, while the other is compiling?
Retrying works.
It does wait with `Blocking waiting for file lock on build directory`, but maybe the locking behavior is not correct?

```
   Compiling server v0.1.0 (/workspace/server)
error: failed to build archive: No such file or directory
error: could not compile `server` (lib) due to previous error
[Finished running. Exit status: 101]
```

```
  = note: mold: fatal: cannot open /workspace/server-[...].rcgu.o: No such file or directory
          collect2: error: ld returned 1 exit status
```

**Comment by passcod** [comment]
Yeah that locking is handled by cargo and RA themselves, watch doesn't have a say. I think cargo introduced [a different locking scheme recently](https://blog.rust-lang.org/2023/12/11/cargo-cache-cleaning.html), maybe that led to a regression here?

**Comment by erikschul** [comment]
Thanks! That sounds plausible.
