### ISSUE TITLE
How to pass environment variables to the cargo run command?

### ISSUE THREAD

**Issue by sylvain-bouchard** [watchexec/cargo-watch#310]
Environment: Mac OS (Sonoma)
cargo-watch version: 8.5.2

Here is the command I am issuing:

`cargo watch -w ./src -x run`

For the cargo run command to work, it has to find a lib installed under:

`/Library/Frameworks/GStreamer.framework/Versions/1.0/lib`

I already have this export in my `.zshrc` file:

`export DYLD_LIBRARY_PATH="/Library/Frameworks/GStreamer.framework/Versions/1.0/lib:$DYLD_LIBRARY_PATH"`

It works if I issue a `cargo run` command directly, but not through a `cargo watch -w ./src -x run`. The above library path is not explored.

How do I set DYLD_LIBRARY_PATH environment variable so that is it visible to the `cargo run` command executed through `cargo watch`? Setting this variable inline to the `cargo watch` command does not work. I have tried many things, including the `--` switch, but nothing works.

**Comment by passcod** [comment]
```
cargo watch -E WHAT=EVER -x run
```

**Comment by passcod** [comment]
Or use `--env-file` to use a dotenv-style file.

**Comment by sylvain-bouchard** [comment]
The -E switch works. Thanks.
