### ISSUE TITLE
`find_local_deps` should filter to the host platform when calling `cargo metadata`

### ISSUE THREAD

**Issue by alex-pinkus** [watchexec/cargo-watch#312]
Unlike most other cargo tools, `cargo metadata` counter-intuitively defaults to including _all_ targets. This means that currently, `cargo-watch` will process (and thus download metadata for) targets other than the one being used for the build -- see `find_local_deps`:

https://github.com/watchexec/cargo-watch/blob/30723ce1ffb3f9ba327a18265f2ff35338a0415a/src/options.rs#L195-L198

When running `cargo watch` without a custom command, [`cargo-check`](https://doc.rust-lang.org/cargo/commands/cargo-check.html) documentation makes clear that this is `check`ing for the host architecture. This means that as long as the user doesn't specify a custom command, `cargo watch` can specify [--filter-platform](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html#output-options) via [MetadataCommand::other_options](https://docs.rs/cargo_metadata/0.15.2/cargo_metadata/struct.MetadataCommand.html#method.other_options) and avoid unnecessary processing.

**Comment by passcod** [comment]
Huh, good to know, thanks!

A PR would be appreciated, otherwise I'll get to it next round of updates.
