### ISSUE TITLE
Feature Request: separate build and run

### ISSUE THREAD

**Issue by clouds56** [watchexec/cargo-watch#322]
I noticed when I run `cargo watch -x run` that anytime we edit a file, the service would be down for a while.
Is it possible to divide it into 3 steps
1. build the target: `cargo build`
2. copy the result in another file `cp target/debug/main target/debug/main.1`
3. run the new file `target/debug/main.1`

And in order to achieve this I have to run 3 cargo watch in 3 process/thread.
Is it possible to simplify this?

**Comment by passcod** [comment]
You should only need 2 cargo watches to hack it:

1. `cargo watch -x build -s 'touch ../trigger'`
2. `cargo watch -w ../trigger -x run`

But in general, it's not cargo watch's responsibility to orchestrate processes. That would open up a lot more surface with dubious ergonomics. You can instead use something like [`pmc`](https://lib.rs/crates/pmc) (as an example, but there are many such tools) to run your service, then:

```
cargo watch -x build -s 'pmc start service'
```

(`pmc start <thing>` does a restart if the thing is already running, your favoured process tool might have a different syntax)
